const DEPARTMENTS = ['MANAGEMENT', 'DEV', 'QA/QC', 'BA', 'ADMIM', 'MARKETING'];
const POSITION = ['LEADER', 'MEMBER', 'ADMIN'];
const STATUS_CANDIDATE = ['PASS', 'FAILED', 'WAIT CONFIRMATION', 'REJECT'];
const STATUS_ASSET = ['FREE', 'BEING USED', 'UNDER REPAIR', 'BROKEN', 'NEW'];
const STATUS_LEAVE = ['APPROVED', 'CONFIRMED', 'REJECTED', 'CANCELED'];
const TYPE_LEAVE = ['OFF', 'REMOTE', 'LATE', 'SOON'];
const STATUS_ACCOUNT_USER = [
  {id: 1, name: 'ACTIVATED'},
  {id: 2, name: 'UNACTIVATED'},
];

export {
  DEPARTMENTS,
  POSITION,
  STATUS_CANDIDATE,
  STATUS_ASSET,
  STATUS_LEAVE,
  TYPE_LEAVE,
  STATUS_ACCOUNT_USER,
};
