const DEPARTMENTS = ['MANAGEMENT', 'DEV', 'QA/QC', 'BA', 'ADMIM', 'MARKETING'];
const POSITION = ['LEADER', 'MEMBER', 'ADMIN'];
const STATUS_CANDIDATE = ['PASS', 'FAILED', 'WAIT CONFIRMATION', 'REJECT'];
const STATUS_ASSET = ['FREE', 'BEING USED', 'UNDER REPAIR', 'BROKEN', 'NEW'];

export {DEPARTMENTS, POSITION, STATUS_CANDIDATE, STATUS_ASSET};
