const DEPARTMENTS = {
  ADMIN: 'ADMIN',
  IT: 'IT',
  DEVELOPER: 'DEVELOPER',
  SALE_MARKETING: 'SALE MARKETING',
  QUALITY_ASSURANCE: 'QUALITY ASSURANCE',
  QUALITY_CONTROL: 'QUALITY CONTROL',
  HUMAN_RESOURCE: 'HUMAN RESOURCE',
  ACCOUNTING_FINANCE: 'ACCOUNTING FINANCE',
};
const POSITION = ['LEADER', 'MEMBER', 'ADMIN'];
const STATUS_CANDIDATE = ['PASS', 'FAILED', 'WAIT CONFIRMATION', 'REJECT'];
const STATUS_ASSET = ['FREE', 'BEING USED', 'UNDER REPAIR', 'BROKEN', 'NEW'];
const STATUS_LEAVE = ['APPROVED', 'REJECTED', 'WAITING', 'CANCELED'];
const TYPE_LEAVE = ['ANNUAL', 'CASUAL', 'REMOTE', 'MATERNITY'];
const STATUS_ASSET_REQUEST = ['PENDING', 'PROCESSING', 'RECEIVED', 'REJECTED', 'CANCELED'];
const STATUS_ACCOUNT_USER = [
  {id: 1, name: 'ACTIVATED'},
  {id: 2, name: 'UNACTIVATED'},
];
const LIST_AUTHORITIES = [
  {title: 'USER', name: 'ROLE_USER'},
  {title: 'ADMIN', name: 'ROLE_ADMIN'},
];
const TYPE_DETAIL_LEAVE = {
  ALL_DAY: 'All day',
  MORNING: 'Morning',
  AFTERNOON: 'Afternoon',
};

export {
  DEPARTMENTS,
  POSITION,
  STATUS_CANDIDATE,
  STATUS_ASSET,
  STATUS_LEAVE,
  TYPE_LEAVE,
  STATUS_ACCOUNT_USER,
  STATUS_ASSET_REQUEST,
  LIST_AUTHORITIES,
  TYPE_DETAIL_LEAVE,
};
